name: goodfood
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^5.0.2
  firebase_crashlytics: ^0.1.0+3
  dio: ">=2.1.8 <6.0.0"
  cached_network_image: ">=0.8.0 <3.0.0"
  flutter_bloc: ">=0.21.0 <9.0.0"
  path_provider: ">=0.5.0+1 <3.0.0"
  url_launcher: ^5.0.2
  sembast: ^1.15.4
  page_transition: ^1.1.0
  location: ^2.3.5
  shimmer: ^1.0.0
  http: ">=0.12.0+2 <0.14.0"
  encrypt: ">=3.1.0"
  crypto: ">=2.0.6"
  flutter_spinkit: ^4.0.0
  badges: ^1.1.0
  extended_nested_scroll_view: ^0.3.6
  animator: ^1.0.0+1
  flutter_svg: ">=0.14.2 <3.0.0"
  material_search: ^0.2.8
  permission_handler: ^3.3.0
  line_icons: ^0.2.0
  flare_flutter: ^1.5.9
  pull_to_refresh: ^1.5.6
  connectivity: ^0.4.4
  auto_size_text: ^2.1.0
  google_maps_flutter: ^0.5.21
  sliding_up_panel: ^0.3.6
  flutter_slidable: ^0.5.4
  flutter_animation_progress_bar: ^1.0.0
  flutter_form_builder: ">=3.5.3 <8.0.0"
  firebase_messaging: ">=5.1.6 <15.0.0"
  pretty_qr_code: ^0.0.8



  built_value: any
  built_collection: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  build: any
  build_config: any
  built_value_generator: any
  json_serializable: ">=3.0.0 <7.0.0"
  build_runner: ">=1.5.0 <3.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/map/style.txt
    - assets/animations/loading.flr
    - assets/animations/okay.flr

    - assets/images/yellow_human.png
    - assets/images/red_human.png
    - assets/images/blue_human.png
    - assets/images/pero.png
    - assets/images/logo.png
    - assets/images/white_logo.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900